AWSTemplateFormatVersion: '2010-09-09'
Description: Unnested stack
Resources:
  HbflVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: 'true'
      Tags:
        - Key: Name
          Value: HBFL-vpc

  HbflVPCSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref HbflVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone:
        !Join
          - ''
          - - !Ref AWS::Region
            - 'a'
      Tags:
        - Key: Name
          Value: HBFL-subnet

  HbflEBApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: HBFL-Web
      Description: "Web interface for the HBFL application"
