AWSTemplateFormatVersion: '2010-09-09'
Description: Template for Trash Panda Buffet game
Resources:
  TrashPandaBuffetVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 11.0.0.0/16
      EnableDnsHostnames: 'true'
      Tags:
        - Key: Name
          Value: TrashPandaBuffet-vpc

  TrashPandaBuffetVPCSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref TrashPandaBuffetVPC
      CidrBlock: 11.0.0.0/24
      AvailabilityZone:
        !Join
          - ''
          - - !Ref AWS::Region
            - 'a'
      Tags:
        - Key: Name
          Value: TrashPandaBuffet-subnet

  TrashPandaBuffetEBApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: TrashPandaBuffet-Web
      Description: "Web interface for the Trash Panda Buffet Game"
